# Generated by Django 4.1.3 on 2022-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('bi', 'Biriyani'), ('pz', 'Pizza'), ('br', 'Burger'), ('sh', 'Shawarma'), ('ch', 'Chicken'), ('pr', 'Paratha'), ('sw', 'Sandwich'), ('ds', 'Dosa'), ('fr', 'Fried Rice'), ('nd', 'Noodles'), ('md', 'Mandhi')], max_length=2)),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('is_veg', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('food_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
