# Generated by Django 4.1.3 on 2023-02-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_orderplaced_customer_alter_orderplaced_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(null=True),
        ),
    ]
