# Generated by Django 4.1.3 on 2023-02-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000020ECF3E0FE0>', max_length=200),
        ),
    ]
